# yaml-language-server: $schema=./schema.json

ban_settings:
  ban_time: 1d
  search_window: 6h
  strikes: 1
  nft_set: yoinkd
monitors:
  nginx:
    inputs:
      - program: journalctl
        args: --follow --output=short-iso CONTAINER_NAME=nginx # My container setups logs to journald
      - program: cat
        args: static-nginx.log # Just look at this file once.
      - program: tail
        args: --follow dynamic-nginx.log # Follow this file for dynamic changes.
    patterns:
      - '${ISO}.+?\]: ${IP4} \S+ \S+ \[[^\]]*\] "[^"]*" 400'
